caddWebsiteMain/urls.py
from django.urls import path
# from .views import (homeView, aboutUsView, contactUsView, coursesView, courseDescriptionView, subCoursesView, subCourseDescriptionView, testimonialsView)
from . import views
from caddWebsiteMain.admin import cadd_site

# urlpatterns = [
#     path('', homeView),
#     path('about/', aboutUsView ), 
#     path('contact/', contactUsView),
#     path('courses/', coursesView), 
#     path('courses/<int:courseId>/', courseDescriptionView),
#     path('subcourses/', subCoursesView ), 
#     path('subcourses/<int:subCourseId>/', subCourseDescriptionView),
#     path('testimonials/', testimonialsView),
# ]

urlpatterns = [
    path('', views.homeView, name='home'),
    path('about/', views.aboutUsView, name='about'),

    path('courseGroup/', views.courseGroupView, name='courseGroup'),
    path('course/<slug:courseGroupSlug>/<slug:courseSlug>/', views.courseDescriptionView, name="courseDescription"),

    path('testimonial/', views.testimonialView, name='testimonial'),
    # path('course/', views.coursesView, name='course'),
    # path('course/<int:courseId>/', views.courseDescriptionView, name='courseDescription'),

    path('privacypolicy/', views.privacypolicy, name='privacypolicy'),
    path('contactUs/', views.contactUsview, name='contact'),
    path('feedback/', views.feedbackView, name='feedback'),
    path('jobfair/', views.jobfairview, name='jobfair'),
    path('etc/', views.etcView, name='etc'),
    path('student-value-adds/', views.studentValueAddsView, name='studentValueAdds'),
    path('placement/', views.placementView, name='placement'),
    path('filterPlacement/', views.placementFilterSearchView, name='filterPlacement'),
    path('loadmore/', views.placementLoadMoreView, name='placementLoadMore'),
    # path('testimonial/', views.testimonialView, name='testimonial'),

]

caddWebsiteProject/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from caddWebsiteMain import urls as mainUrls
from caddWebsiteMain.admin import cadd_site

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(mainUrls)),
    path('caddadmin/', cadd_site.urls),
    path('summernote/', include('django_summernote.urls'))
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

caddWebsiteMain/models.py
from django.db import models
from datetime import datetime 

from django.utils.text import slugify

# class CourseGroup(models.Model):
#   courseGroupName = models.CharField(max_length=255)

# class CourseIndex(models.Model):
#   courseGroupId = models.ForeignKey(CourseGroup, on_delete=models.SET_NULL, null=True)
#   courseName = models.CharField(max_length = 100)

#   def __str__(self):
#     return self.courseName

# class CourseContentTitle(models.Model):
#   courseId = models.ForeignKey(CourseIndex, on_delete = models.CASCADE)
#   courseContentTitle = models.CharField(max_length=100)
  
# class CourseContentDescription(models.Model):
#   courseContentTitleId = models.ForeignKey(CourseContentTitle, on_delete = models.CASCADE)
#   courseContentDescription = models.TextField()



# class SubCourseIndex(models.Model):
#   subCourseName = models.CharField(max_length = 100)

#   def __str__(self):
#     return self.subCourseName
  
# class SubCourseContentTitle(models.Model):
#   subCourseId = models.ForeignKey(SubCourseIndex, on_delete = models.CASCADE)
#   subCourseContentTitle = models.CharField(max_length=100)

# class SubCourseContentDescription(models.Model):
#   subCourseContentTitleId = models.ForeignKey(SubCourseContentTitle, on_delete=models.CASCADE)
#   subCourseContentDescription = models.TextField()

# class CourseWithSubCourse(models.Model):
#   courseId = models.ForeignKey(CourseIndex, on_delete=models.CASCADE)
#   subCourseId = models.ForeignKey(SubCourseIndex, on_delete=models.CASCADE)



class CourseGroup(models.Model):
  courseGroupName = models.CharField(max_length=255)
  courseGroupSlug = models.SlugField(max_length=255, unique=True, null=True, blank=True)

  def save(self, *args, **kwargs):
    if not self.courseGroupSlug:
      self.courseGroupSlug = slugify(self.courseGroupName)
    super(CourseGroup, self).save(*args, **kwargs)


  def __str__(self):
    return self.courseGroupName





class Core(models.Model):
  courseGroupId = models.ForeignKey(CourseGroup, on_delete=models.SET_NULL, null=True)
  coreName = models.CharField(max_length = 100)
  coreImage = models.ImageField(upload_to='caddWebsiteMain/courseImages/', blank=True, null=True)
  coreSlug = models.SlugField(max_length=255, unique=True, blank=True, null=True)

  def save(self, *args, **kwargs):
    if not self.coreSlug:
      self.coreSlug = slugify(self.coreName)
    super(Core, self).save(*args, **kwargs)

  def __str__(self):
    return self.coreName

class Module(models.Model):
  courseGroupId = models.ForeignKey(CourseGroup, on_delete=models.SET_NULL, null=True)
  moduleName = models.CharField(max_length = 100)
  moduleImage = models.ImageField(upload_to='caddWebsiteMain/courseImages/', blank=True, null=True)
  cores = models.ManyToManyField(Core, related_name='contains', blank=True)  
  moduleSlug = models.SlugField(max_length=255, blank=True, null=True, unique=True)

  def save(self, *args, **kwargs):
    if not self.moduleSlug:
      self.moduleSlug = slugify(self.moduleName)
    super(Module, self).save(*args,**kwargs)

  def __str__(self):
    return self.moduleName
  
class CoreDescription(models.Model):
  core = models.ForeignKey(Core, on_delete = models.CASCADE)
  descriptionTitle = models.CharField(max_length = 100)
  description = models.TextField()

  def __str__(self):
    return self.descriptionTitle

class ModuleDescription(models.Model):
  module = models.ForeignKey(Module, on_delete = models.CASCADE)
  descriptionTitle = models.CharField(max_length = 100)
  description = models.TextField()

  def __str__(self):
    return self.descriptionTitle

class TopStreamDescription(models.Model):
  coreDescriptionId = models.ForeignKey(CoreDescription, on_delete=models.CASCADE, null=True)
  logoImage = models.ImageField(upload_to='courses/', null=True, blank=True)
  descriptionTitle = models.CharField(max_length=255, null=True, blank=True)
  description = models.TextField(blank=True, null=True)






class CaddBasicDetails(models.Model):
  address = models.TextField()
  email = models.CharField(max_length=300)
  youtube = models.CharField(max_length=300)
  facebook = models.CharField(max_length=300)
  twitter = models.CharField(max_length=300)
  instagram = models.CharField(max_length=300)
  linkedin = models.CharField(max_length=300)
  phoneNumber = models.CharField(max_length=100)





class Advertisements(models.Model):
  name = models.CharField(max_length=200)
  banner = models.ImageField(upload_to='advertisements/')
  link = models.CharField(max_length=200)

  def __str__(self):
    return self.name


""" dont touch this below part it is working perfectly"""

class AboutUs(models.Model):
  descriptionTitle = models.CharField(max_length=100)
  description = models.TextField()
  image = models.ImageField(default=None, null=True)

  def __str__(self):
    return str(self.descriptionTitle)
  
# class projects(models.Model):
#   superCourseId = models.ForeignKey(courseIndex, on_delete = models.CASCADE)
#   projectTitle = models.CharField(max_length=100)
#   projectDescription = models.TextField()
  
class Testimonial(models.Model):
  feedback = models.TextField()
  studentName = models.CharField(max_length=100)
  ratings = models.IntegerField()
  
# class Partners(models.Model):
#   productName = models.CharField(max_length=100)
#   description = models.TextField()
#   partnerName = models.CharField(max_length=100)
#   partnerLink = models.CharField(max_length=100)

#   def __str__(self):
#     return str(self.partnerName)


'''This is the finalized correct model for contactUs'''
class Enquiry(models.Model):
  name = models.CharField(max_length=100)
  email = models.EmailField()
  phone = models.IntegerField()
  subject = models.TextField()

class Feedback(models.Model):
  qualityOfTraining = models.IntegerField()
  qualityOfTrainer = models.IntegerField()
  qualityOfTrainingMaterials = models.IntegerField()
  overallExperience = models.IntegerField()
  

class JobOpportunities(models.Model):
  jobRole = models.CharField(max_length=100)
  companyName = models.CharField(max_length=100)
  location = models.TextField(blank=True)
  mainLocation = models.CharField(max_length=100, null=True, blank=True)
  companyLogo = models.ImageField(upload_to ='images/placements/')
  companyWebsiteLink = models.CharField(max_length=200, blank=True, null=True)
  category = models.CharField(max_length=100)
  salary = models.IntegerField()
  education = models.CharField(max_length=200)
  department = models.CharField(max_length=200, blank=True, null=True)
  experience = models.CharField(max_length=100, blank=True, null=True)
  keyFeatures = models.TextField(blank=True)
  lastDate = models.DateField(null=True)

  def __str__(self):
    return self.jobRole+" "+self.companyName
  

caddWebsiteMain/templates/courseGroup.html
{% extends 'caddWebsite/base.html' %} 

{% load static %}

{% block linkcss %}
  <link rel="stylesheet" type="text/css" href="{% static 'caddWebsiteMain\courseGroup\courseGroup.css' %}">
  <!-- <script src="../cadd.js"></script> -->
{% endblock %}

  
{% block navbar %}
{% include 'navbar.html' %}
{% endblock %}


{% block content %}
  <header>
    <h1>Our Courses</h1>
  </header>
  <main>
    
    {% for obj in objects %}
    <div class="course">
      <!-- <img src="course1.jpg" alt="Course 1"> -->
      <h2>{{obj.courseGroupName}}</h2>
      <!-- <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean vitae felis eu mi hendrerit placerat.</p> -->
      <ul>
        {% if obj.core_set %}
        {% for li_object in obj.core_set.all %}
        <li><a href="/course/{{obj.courseGroupSlug}}/{{li_object.coreSlug}}">{{li_object}}</a></li>
        
        {% endfor %}
        {% endif %}
        {% if obj.module_set.all %}
        {% for li_object in obj.module_set.all %}
        <li><a href="/course/{{obj.courseGroupSlug}}/{{li_object.moduleSlug}}">{{li_object}}</a></li>
        
        {% endfor %}
        {% endif %}
      </ul>
    </div>
    {% endfor %}
    <!-- <div class="course">
      <img src="course1.jpg" alt="Course 1">
      <h2>Product Design Analysis</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean vitae felis eu mi hendrerit placerat.</p>
      <ul>
        <li><a href="#">AutoCAD For Mechanical Engineers </a></li>
        <li><a href="#">Solid Works</a></li>
        <li><a href="#">Revit MEP</a></li>
        <li><a href="#">ANSYS</a></li>
        <li><a href="#">CREO</a></li>
        <li><a href="#">NX CAD</a></li>
        
      </ul>
      <a  class="a" href="#">Learn More</a>
    </div>
    <div class="course">
      <img src="course1.jpg" alt="Course 1">
      <h2>Our Courses</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean vitae felis eu mi hendrerit placerat.</p>
      <ul>
        <li><a href="#">Proficient Certificate</a></li>
        <li><a href="#">Master Certificate</a></li>
        <li><a href="#">Expert Certificate</a></li>
        <li><a href="#">sub courses</a></li>
        <li><a href="#">sub courses</a></li>
      </ul>
      <a  class="a" href="#">Learn More</a>
    </div>
    <div class="course">
      <img src="course1.jpg" alt="Course 1">
      <h2>Our Courses</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean vitae felis eu mi hendrerit placerat.</p>
      <ul>
        <li><a href="#">Proficient Certificate</a></li>
        <li><a href="#">Master Certificate</a></li>
        <li><a href="#">Expert Certificate</a></li>
        <li><a href="#">sub courses</a></li>
        <li><a href="#">sub courses</a></li>
      </ul>
      <a  class="a" href="#">Learn More</a>
    </div>
    <div class="course">
      <img src="course1.jpg" alt="Course 1">
      <h2>Our Courses</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean vitae felis eu mi hendrerit placerat.</p>
      <ul>
        <li><a href="#">Proficient Certificate</a></li>
        <li><a href="#">Master Certificate</a></li>
        <li><a href="#">Expert Certificate</a></li>
        <li><a href="#">sub courses</a></li>
        <li><a href="#">sub courses</a></li>
      </ul>
      <a  class="a" href="#">Learn More</a>
    </div>
    <div class="course">
      <img src="course1.jpg" alt="Course 1">
      <h2>Our Courses</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean vitae felis eu mi hendrerit placerat.</p>
      <ul>
        <li><a href="#">Proficient Certificate</a></li>
        <li><a href="#">Master Certificate</a></li>
        <li><a href="#">Expert Certificate</a></li>
        <li><a href="#">sub courses</a></li>
        <li><a href="#">sub courses</a></li>
      </ul>
      <a  class="a" href="#">Learn More</a>
    </div>
    <div class="course">
      <img src="course1.jpg" alt="Course 1">
      <h2>Our Courses</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean vitae felis eu mi hendrerit placerat.</p>
      <ul>
        <li><a href="#">Proficient Certificate</a></li>
        <li><a href="#">Master Certificate</a></li>
        <li><a href="#">Expert Certificate</a></li>
        
      </ul>
      <a  class="a" href="#">Learn More</a>
    </div>
   -->
  </main>
{% endblock %}


{% block footer %} 
{% include 'footer.html' %} 
{% endblock %}

caddWebsiteMain/templates/footer.html
<footer class="cadd-footer-footer">
    <div class="cadd-footer-container">
       <div class="cadd-footer-row">
            <div class="cadd-footer-footer-col">
                 <h4>Company</h4>
                 <ul>
                     <li><a href="/about">About Us</a></li>
                     <li><a href="/placement">Placements</a></li>
                     <li><a href="https://caddcentre.com/blog/">Blog</a></li>
                     <li><a href="/privacypolicy">Privacy Policy</a></li>
                     <li><a href="/contactUs">Contact Us</a></li>
                     <li><a href="/feedback">Feedback</a></li>
                     <li><a href="/jobfair">Job Fair</a></li>
                     
                 </ul>
            </div>
            <div class="cadd-footer-footer-col">
                 <h4>Community & Events</h4>
                 <ul>
                     <li><a href="/etc">Engineering, Technology & Careers (ETC)</a></li>
                     <li><a href="/student-value-adds">Student-Value-Adds</a></li>
                 </ul>
                 <h4 style="margin-top: 20px;">Certifications</h4>
                 <ul>
                    {% for obj in certificateCourses.core_set.all %}
                     <li><a href="/course/{{certificateCourses.courseGroupSlug}}/{{obj.coreSlug}}">{{obj.coreName}}</a></li>
                     <!-- <li><a href="#">Advance Certificate</a></li>
                     <li><a href="#">Masters Certificate</a></li>
                     <li><a href="#">Expert Certificate</a></li> -->
                    {% endfor %}
                 </ul>
            </div>
            <div class="cadd-footer-footer-col">
                 <h4>Hybrid Courses</h4>
                 <ul>
                    {% for obj in hybridCourses.module_set.all %}
                     <li><a href="/course/{{hybridCourses.courseGroupSlug}}/{{obj.moduleSlug}}">{{obj.moduleName}}</a></li>
                     <!-- <li><a href="#">CATIA Kinematics</a></li>
                     <li><a href="#">Hypermesh</a></li>
                     <li><a href="#">Autodesk Inventor</a></li>
                     <li><a href="#">Mastercam</a></li>
                     <li><a href="#">NX CAM</a></li>
                     <li><a href="#">PDMS</a></li>
                     <li><a href="#">GD&T</a></li>
                     <li><a href="#">3D Printing</a></li>
                     <li><a href="#">Microstation</a></li>
                     <li><a href="#">NX NASTRAN</a></li>
                     <li><a href="#">MX ROAD</a></li>
                     <li><a href="#">ANSYS Fluent</a></li> -->
                     {% endfor %}
                 </ul>
             </div>
             <div class="cadd-footer-footer-col cadd-footer-contact">
                 <h4>Get in touch</h4>
                 <ul class="cadd-footer-grid">
                     <li><a href="{{caddBasicDetails.instagram}}" target="_blank"><i class="fa-brands fa-instagram"></i></a></li>
                     <li><a href="{{caddBasicDetails.facebook}}" target="_blank"><i class="fa-brands fa-square-facebook"></i></a></li>
                     <li><a href="tel:{{caddBasicDetails.phoneNumber}}"><i class="fa-solid fa-phone"></i></i></a></li>
                     <li><a href="{{caddBasicDetails.youtube}}" target="_blank"><i class="fa-brands fa-youtube"></i></a></li>
                 </ul>
                 
             </div>
       </div>
    </div>
 </footer>
 <div class="cadd-footer-footer-last">
     <p>Copyright © 2023 <a href="https://www.cadd.net.in/">CADD Centre.</a> All Rights Reserved.</p>
     
 </div>

caddWebsiteMain/templates/home.html
{% extends 'caddWebsite/base.html' %} 

{% load static %}

{% block linkcss %} 
<link
rel="stylesheet"
href="https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.carousel.min.css"
/>
<link
rel="stylesheet"
href="https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.theme.min.css"
/>
<link rel="stylesheet" href="{% static 'caddWebsiteMain/home/home.css' %}">
<link href="https://fonts.googleapis.com/css2?family=Rampdvart+One&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Rubik+Dirt&display=swap" rel="stylesheet">

{% endblock %}

{% block navbar %}
{% include 'navbar.html' %}
{% endblock %}


{% block content %}
{% for message in messages %} 
{{message}}
{% endfor %}
<section id="cadd-description">
    <div class="banner"><img src="/media/caddWebsiteMain/home/CADD-Banner.png" alt="" /></div>
    <div class="whycadd-description">
      <h1>Welcome to CADD Center</h1>
      <p>
        As Asia's biggest network of CAD Training Centre in Chennai. We offer
        CAD Training with job placement that help students add value to their
        career with globally recognized training and certifications. We enlist
        most sought-after courses for everyone – designer, drafter,
        administrator , or a programmer. Hence its very essential to do CAD
        software courses in the best CADD Training Centre in Chennai.
      </p>
      <h1>Why CADD Center?</h1>
      <p>
        With rapid advancements in Cad technologies, major industries engaged
        in engineering services are preferring CAD software in to their
        everyday work. Our CADD Centre provides software solutions across a
        variety of Engineering branches from Civil, Construction, Mechanical,
        Geotechnical, Architecture to Designing and Animations.
        <br /><br />
        Some of our top CAD software training courses that are grabbing
        attractions of the major engineering industries are- AutoCAD, ANSYS
        SpaceClaim, SolidWorks, Revit MEP, etc. Thus, CAD software's are
        ruling the industries all over the world and have brought dramatic
        changes in many firms by automating the process of the development
        life cycle for a product.
        <a href="/about"> Learn More →</a>
      </p>
    </div>
    <div class="world-class-division">
      <h1>World class training, World over</h1>
      <div class="cadd-achievement-content-box">
        <div class="content-box-1">
          <h2>2M+</h2>
          <p>Engineers and Professionals trained</p>
        </div>
        <div class="content-box-2 content-box">
          <h2>730</h2>
          <p>Training centres - Asia's biggest network</p>
        </div>
        <div class="content-box-3 content-box">
          <h2>24</h2>
          <p>Global locations</p>
        </div>
        <div class="content-box-4 content-box">
          <h2>100+</h2>
          <p>Industry-ready courses</p>
        </div>
      </div>
    </div>
  </section>
  <section>
    <h1 class="testimonial-title">Hear from our students</h1>
    <section class="testimonial">
      <div class="content">
        <div class="container">
          <div class="box box1">
            <h1 class="testimonial-title-1">
              Straight from our learners' hearts!
            </h1>
            <p>
              It is always joyful to enable passionate learners in their
              journey to success. Watch our learners share their experiences
              with learning at CADD Centre
            </p>
          </div>
          <div class="box box2">
            <a
              href="https://www.youtube.com/playlist?list=PL9ovgj0ugeztxJiva8ZbSnYXzF0r1auvT"
              target="_blank"
              ><img
                class="yts"
                src="https://caddcentre.com/assets/images/youtubeTestimonial.png
                      "
                alt="yts"
            /></a>
          </div>
        </div>
      </div>
    </section>
  </section>
  <section id="cadd-card-slider">
    <div class="cadd-first-card-slider">
      <h1>Top Stream Certification Courses</h1>
      <div class="owl-carousel" 
      style="display: flex;
      justify-content: space-between;
      padding:30px;">
      {% for obj in topStreamCourse.core_set.all %}
        <div class="card">
          <img
            src="{{obj.coreImage.url}}"
            alt="cadd-first-job-pakka"
          />
          <h2>{{obj.coreName}}</h2>
          <div class="cadd-card-short-details">
            <span><img src="/media/caddWebsiteMain/home/cadd-duration.svg" />40hrs</span>
            <span><img src="/media/caddWebsiteMain/home/cadd-mode.svg" />In-Centre</span>
          </div>
          <p>
            Project Based assessment <span>|</span>World Class Courseware
            <span>|</span>Industry recognized support <span>|</span>Placement
            support
          </p>
          <button><a href="/course/{{topStreamCourse.courseGroupSlug}}/{{obj.coreSlug}}">Know More</a></button>
        </div>
        {% endfor %}
        {% for obj in projectManagementCourse.module_set.all %}
        <div class="card">
          <img
            src="{{obj.moduleImage.url}}"
            alt="cadd-first-job-pakka"
          />
          <h2>{{obj.moduleName}}</h2>
          <div class="cadd-card-short-details">
            <span><img src="/media/caddWebsiteMain/home/cadd-duration.svg" />50hrs</span>
            <span><img src="/media/caddWebsiteMain/home/cadd-mode.svg" />In-Centre</span>
          </div>
          <p>
            Project Based assessment <span>|</span>World Class Courseware
            <span>|</span>Industry recognized support <span>|</span>Placement
            support
          </p>
          <button><a href="/course/{{projectManagementCourse.courseGroupSlug}}/{{obj.moduleSlug}}">Know More</a></button>
        </div>
        {% endfor %}
      </div>
    </div>
      <div class="cadd-first-card-slider">
        <h1>Trending Technology Courses</h1>
       <div class="owl-carousel" 
      style="display: flex;
      justify-content: space-around;
      padding:30px;">
              {% for obj in productDesignCourse.module_set.all %}
              <div class="card">
                <img
                  src="{{obj.moduleImage.url}}"
                  alt="cadd-first-job-pakka"
                />
                <h2>{{obj.moduleName}}</h2>
                <div class="cadd-card-short-details">
                  <span><img src="/media/caddWebsiteMain/home/cadd-duration.svg" />50hrs</span>
                  <span><img src="/media/caddWebsiteMain/home/cadd-mode.svg" />In-Centre</span>
                </div>
                <p>
                  Project Based assessment <span>|</span>World Class Courseware
                  <span>|</span>Industry recognized support <span>|</span>Placement
                  support
                </p>
                <button><a href="/course/{{productDesignCourse.courseGroupSlug}}/{{obj.moduleSlug}}">Know More</a></button>
              </div>
              {% endfor %}
              {% for obj in informationTechnologyCourse.module_set.all %}
              <div class="card">
                <img
                  src="{{obj.moduleImage.url}}"
                  alt="cadd-first-job-pakka"
                />
                <h2>{{obj.moduleName}}</h2>
                <div class="cadd-card-short-details">
                  <span><img src="/media/caddWebsiteMain/home/cadd-duration.svg" />50hrs</span>
                  <span><img src="/media/caddWebsiteMain/home/cadd-mode.svg" />In-Centre</span>
                </div>
                <p>
                  Project Based assessment <span>|</span>World Class Courseware
                  <span>|</span>Industry recognized support <span>|</span>Placement
                  support
                </p>
                <button><a href="/course/{{informationTechnologyCourse.courseGroupSlug}}/{{obj.moduleSlug}}">Know More</a></button>
              </div>
              {% endfor %}
       </div>
      </div>
    </div>
  </section>

{% endblock %} 

{% block footer %} 
{% include 'footer.html' %} 
{% endblock %}

caddWebsiteMain/templates/navbar.html
<div class="nav">
    <input type="checkbox" id="nav-check">
    <!-- <div class="nav-header">
      <div class="nav-title">
        JoGeek
      </div>
    </div> -->
<div class="nav-btn">
    <label for="nav-check">
      <span></span>
      <span></span>
      <span></span>
    </label>
  </div>
  
  <div class="nav-links">
    <a href="/" >Home</a>
    <a href="/about/" >About Us</a>
    <a href="/courseGroup/">Ourcourses</a>
    <a href="/placement/" >Placements</a>
    <a href="/testimonial/" >Testimonials</a>
    <a href="https://caddcentre.com/blog/" >Blog</a>
    <a href="/contactUs/" >Contact Us</a>
  </div>
</div>